name: "🚀 CI/CD Pipeline"

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: 20
  VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
  VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
  VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
  VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
  VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

# lets us upload SARIF to the Security tab
permissions:
  contents: read
  pull-requests: write
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # ---------- Secrets (OWASP A08) ----------
  gitleaks:
    name: Secrets scan (A08)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run Gitleaks (non-blocking)
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true        # <-- keep the check green even if leaks
      - name: Upload Gitleaks SARIF (if present)
        if: always() && hashFiles('results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif

  # ---------- SAST (OWASP A01–A10) ----------
  semgrep:
    name: SAST OWASP Top 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/semgrep
          key: semgrep-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            semgrep-${{ runner.os }}-
      - name: Install Semgrep CLI
        run: |
          python -m pip install --upgrade pip
          pip install "semgrep>=1.73.0"
      - name: Run Semgrep (non-blocking) and write SARIF
        run: |
          semgrep \
            --config p/owasp-top-ten \
            --exclude node_modules --exclude dist --exclude build --exclude .git \
            --sarif --output semgrep.sarif || true   # <-- never fail the step
      - name: Upload Semgrep SARIF (if present)
        if: always() && hashFiles('semgrep.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

  # ---------- Lint • Test • Build ----------
  test:
    name: Lint • Test • Build
    runs-on: ubuntu-latest
    needs: [gitleaks, semgrep]   # still run security jobs first
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci --no-audit --progress=false
      - run: npm run ci
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: ignore
          retention-days: 3

  # ---------- Deploy ----------
  deploy:
    name: Deploy to Firebase Hosting
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci --no-audit --progress=false
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          channelId: live
          projectId: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
      - name: Print Hosting URL (and add to summary)
        run: |
          echo "Deployed to: https://${{ secrets.VITE_FIREBASE_PROJECT_ID }}.web.app"
          {
            echo "### Deployment"
            echo "- Live: https://${{ secrets.VITE_FIREBASE_PROJECT_ID }}.web.app"
          } >> $GITHUB_STEP_SUMMARY
