# .github/workflows/owasp-lite.yml
name: OWASP Lite (Semgrep + Gitleaks)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  gitleaks:   # ---- Secrets scanning (OWASP A08) ----
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          # Scans working tree only; avoids noisy history hits while you rotate keys.
          args: "detect --no-git --redact --verbose"

  semgrep:    # ---- SAST (OWASP Top 10) ----
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep CLI
        run: |
          python3 -m pip install --upgrade pip
          pip3 install "semgrep>=1.73.0"

      - name: Run Semgrep (OWASP Top 10) and produce SARIF
        run: |
          semgrep \
            --config p/owasp-top-ten \
            --exclude node_modules --exclude dist --exclude .git \
            --error \
            --sarif --output semgrep.sarif

      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
